"""empty message

Revision ID: 06959ec56f75
Revises: 
Create Date: 2022-04-19 16:42:36.277267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06959ec56f75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('loanid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loan_status', sa.String(length=255), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('interestrate', sa.Integer(), nullable=True),
    sa.Column('loanamount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loanid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    # ### end Alembic commands ###
