"""empty message

Revision ID: 1579b15fba99
Revises: de35430a904c
Create Date: 2022-04-12 02:55:22.601370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1579b15fba99'
down_revision = 'de35430a904c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphicalanalytics',
    sa.Column('loanid', sa.String(length=80), nullable=False),
    sa.Column('loanamount', sa.Integer(), nullable=True),
    sa.Column('interestrate', sa.Integer(), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loanid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graphicalanalytics')
    # ### end Alembic commands ###
