"""empty message

Revision ID: 17ccf628d79e
Revises: 
Create Date: 2022-04-11 22:12:44.955431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ccf628d79e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('sid', sa.String(length=80), nullable=True),
    sa.Column('imageid', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('imageid')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=80), nullable=True),
    sa.Column('phonenumber', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(length=80), nullable=True),
    sa.Column('trn', sa.String(length=1000), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('image')
    # ### end Alembic commands ###
