"""empty message

Revision ID: 26986f4716f7
Revises: f0b43d832415
Create Date: 2022-04-19 22:58:37.223363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26986f4716f7'
down_revision = 'f0b43d832415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('loanid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loan_type', sa.String(length=255), nullable=True),
    sa.Column('loan_status', sa.String(length=255), nullable=True),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('interestrate', sa.Integer(), nullable=True),
    sa.Column('loanamount', sa.Integer(), nullable=True),
    sa.Column('moratorium', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('loanid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    # ### end Alembic commands ###
