"""empty message

Revision ID: 3d3b8b979aee
Revises: ae00207702c9
Create Date: 2022-04-03 20:53:36.406539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d3b8b979aee'
down_revision = 'ae00207702c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gurantor', sa.Column('guarantor_occupation', sa.String(length=80), nullable=True))
    op.add_column('gurantor', sa.Column('guarantor_phonenumber', sa.Integer(), nullable=True))
    op.add_column('gurantor', sa.Column('guarantor_salary', sa.Float(), nullable=True))
    op.add_column('gurantor', sa.Column('guarantor_address', sa.String(length=255), nullable=True))
    op.drop_column('gurantor', 'gurantor_occupation')
    op.drop_column('gurantor', 'gurantor_phonenumber')
    op.drop_column('gurantor', 'gurantor_address')
    op.drop_column('gurantor', 'gurantor_salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gurantor', sa.Column('gurantor_salary', mysql.FLOAT(), nullable=True))
    op.add_column('gurantor', sa.Column('gurantor_address', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('gurantor', sa.Column('gurantor_phonenumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('gurantor', sa.Column('gurantor_occupation', mysql.VARCHAR(length=80), nullable=True))
    op.drop_column('gurantor', 'guarantor_address')
    op.drop_column('gurantor', 'guarantor_salary')
    op.drop_column('gurantor', 'guarantor_phonenumber')
    op.drop_column('gurantor', 'guarantor_occupation')
    # ### end Alembic commands ###
