"""empty message

Revision ID: 4979550ebfda
Revises: 3d3b8b979aee
Create Date: 2022-04-03 20:54:24.787113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4979550ebfda'
down_revision = '3d3b8b979aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guarantor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('guarantor_occupation', sa.String(length=80), nullable=True),
    sa.Column('guarantor_phonenumber', sa.Integer(), nullable=True),
    sa.Column('guarantor_salary', sa.Float(), nullable=True),
    sa.Column('guarantor_address', sa.String(length=255), nullable=True),
    sa.Column('loanid', sa.String(length=80), nullable=True),
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', 'sid')
    )
    op.drop_table('gurantor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gurantor',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('loanid', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('sid', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('guarantor_occupation', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('guarantor_phonenumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('guarantor_salary', mysql.FLOAT(), nullable=True),
    sa.Column('guarantor_address', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', 'sid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('guarantor')
    # ### end Alembic commands ###
