"""empty message

Revision ID: 584cafe50a28
Revises: 06959ec56f75
Create Date: 2022-04-19 19:02:20.778390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584cafe50a28'
down_revision = '06959ec56f75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('sid', sa.String(length=80), nullable=True),
    sa.Column('loanid', sa.String(length=80), nullable=True),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.String(length=80), nullable=True),
    sa.Column('paymentid', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('paymentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
