"""empty message

Revision ID: 663366e066d4
Revises: 621c016ed26a
Create Date: 2022-04-10 17:46:37.642168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663366e066d4'
down_revision = '621c016ed26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=80), nullable=True),
    sa.Column('phonenumber', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(length=80), nullable=True),
    sa.Column('trn', sa.String(length=1000), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
