"""empty message

Revision ID: 6a627bd86cac
Revises: 17ccf628d79e
Create Date: 2022-04-12 02:51:34.539059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a627bd86cac'
down_revision = '17ccf628d79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graphicalanalytics', sa.Column('loanamount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graphicalanalytics', 'loanamount')
    # ### end Alembic commands ###
