"""empty message

Revision ID: ae00207702c9
Revises: cbd4696cce97
Create Date: 2022-04-03 20:43:27.865989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae00207702c9'
down_revision = 'cbd4696cce97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graphicalanalytics',
    sa.Column('loanid', sa.String(length=80), nullable=False),
    sa.Column('sid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loanid')
    )
    op.add_column('loanprioritization', sa.Column('interest', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loanprioritization', 'interest')
    op.drop_table('graphicalanalytics')
    # ### end Alembic commands ###
