"""empty message

Revision ID: b85d003a21e3
Revises: 5d64de5d9c94
Create Date: 2022-05-10 20:29:19.741993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85d003a21e3'
down_revision = '5d64de5d9c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminlog',
    sa.Column('logid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logdata', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('logid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adminlog')
    # ### end Alembic commands ###
