"""empty message

Revision ID: cbd4696cce97
Revises: 
Create Date: 2022-03-28 18:36:48.644443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd4696cce97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('student_name', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('student_address', sa.String(length=255), nullable=True),
    sa.Column('student_dob', sa.Date(), nullable=True),
    sa.Column('student_signature', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('creditscore',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('cscore', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_table('gurantor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('gurantor_occupation', sa.String(length=80), nullable=True),
    sa.Column('gurantor_phonenumber', sa.Integer(), nullable=True),
    sa.Column('gurantor_salary', sa.Float(), nullable=True),
    sa.Column('gurantor_address', sa.String(length=255), nullable=True),
    sa.Column('loanid', sa.String(length=80), nullable=True),
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', 'sid')
    )
    op.create_table('loan',
    sa.Column('loanid', sa.String(length=80), nullable=False),
    sa.Column('loan_type', sa.Integer(), nullable=True),
    sa.Column('loan_status', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('loanid')
    )
    op.create_table('loanadmin',
    sa.Column('loan_admin_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('loan_admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('loanprioritization',
    sa.Column('loanid', sa.String(length=80), nullable=False),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('loanid')
    )
    op.create_table('payment',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('loanid', sa.String(length=80), nullable=False),
    sa.Column('payment_amount', sa.Integer(), nullable=True),
    sa.Column('paymemt_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('sid', 'loanid')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('sex', sa.String(length=80), nullable=True),
    sa.Column('phonenumber', sa.Integer(), nullable=True),
    sa.Column('sid', sa.String(length=80), nullable=True),
    sa.Column('trn', sa.String(length=1000), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentssignup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('university',
    sa.Column('sid', sa.String(length=80), nullable=False),
    sa.Column('university_name', sa.Integer(), nullable=True),
    sa.Column('student_major', sa.String(length=255), nullable=True),
    sa.Column('student_faculty', sa.String(length=255), nullable=True),
    sa.Column('student_tuition', sa.String(length=255), nullable=True),
    sa.Column('univeristy_contact', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('university')
    op.drop_table('studentssignup')
    op.drop_table('student')
    op.drop_table('payment')
    op.drop_table('loanprioritization')
    op.drop_table('loanadmin')
    op.drop_table('loan')
    op.drop_table('gurantor')
    op.drop_table('creditscore')
    op.drop_table('contract')
    # ### end Alembic commands ###
